---

- hosts: 127.0.0.1
  connection: local
  vars_files:
    - external_vars.yml
  tasks:
    - name: Check directory for .tar.gz files
      find:
        path: "{{ imagedir }}"
        patterns: '*.tar.gz'
      register: images_to_import

    - meta: end_play
      when: images_to_import.files.0 is not defined

    - include: image_import.yml
      with_items: "{{ images_to_import.files }}"
